sudo: required

services:
  - docker

before_install:
  - docker-compose -v

install:
  - docker-compose run php composer install -n
  - docker-compose run php ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
  - docker-compose run -e AWS_ACCESS_KEY=$AWS_ODBC_KEY -e AWS_SECRET_KEY=$AWS_ODBC_SECRET php php docker/downloadOdbcDriver.php
  - docker-compose run php php ./tests/loadS3.php

script:
 - docker-compose run tests