sudo: required

language: bash

services:
  - docker

before_install:
  - docker-compose -v

install:
  - docker-compose up -d mysql # boot mysql now to be ready when tests are started
  - docker-compose run --rm drivers-download composer install
  - docker-compose run --rm drivers-download php docker/downloadOdbcDriver.php
  - docker-compose build tests
  - docker-compose run --rm tests php ./tests/loadS3.php

script:
 - docker-compose run --rm tests ./vendor/bin/phpcs --standard=psr2 --ignore=vendor -n .
 - docker-compose run --rm tests php ./vendor/bin/phpunit tests/Mysql
 - docker-compose run --rm tests php ./vendor/bin/phpunit tests/Redshift
 - docker-compose run --rm tests php ./vendor/bin/phpunit tests/Snowflake
