version: "2"

services:

  tests:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    command: sh -c 'composer install -n && php ./vendor/bin/phpunit'
    tty: true
    stdin_open: true
    links:
      - mysql
    environment:
      - REDSHIFT_HOST
      - REDSHIFT_USER
      - REDSHIFT_PORT
      - REDSHIFT_DATABASE
      - REDSHIFT_PASSWORD
      - SNOWFLAKE_HOST
      - SNOWFLAKE_PORT
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DATABASE
      - SNOWFLAKE_WAREHOUSE
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
      - MYSQL_PORT_3306_TCP_ADDR
      - MYSQL_ENV_MYSQL_DATABASE
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_DATABASE: tests
      MYSQL_ROOT_PASSWORD: password

  php:
    image: keboola/docker-php56-all-db
    volumes:
        - .:/code
    working_dir: /code
    environment:
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - AWS_S3_BUCKET
      - AWS_REGION
