tests:
  build: .
  volumes:
    - .:/code
  working_dir: /code
  command: sh -c 'composer install -n && php ./vendor/bin/phpunit'
  tty: true
  stdin_open: true
  links:
    - mysql

mysql:
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: tests
    MYSQL_ROOT_PASSWORD: password